version = 0.1

[default.deploy.parameters]
stack_name = "coupon-manager"
resolve_s3 = true
s3_prefix = "coupon-manager"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\" GoogleClientId=\"772799251248-54645l59rud8uch84opelnteqhmb395t.apps.googleusercontent.com\" WebAppUrl=\"http://localhost:5173\""
confirm_changeset = true
fail_on_empty_changeset = false
image_repositories = []

[default.global.parameters]
region = "us-east-1"
